version: 0.2

phases:
  pre_build:
    commands:
      - echo Install packages and create build...
      - yarn
  build:
    commands:
      - echo Start App...
      - yarn build
artifacts:
  files:
    - '**/*'
  base-directory: '.'
  discard-paths: no
  exclude-paths:
    - src/
    - tests/
    - jest.config.ts/
    - .editorconfig/
    - tsconfig.json/
    
